export const DB = {
  tables: {
    productionRecords: 'production_records',
    gasRecords: 'gas_records',
    gasDailyReadings: 'gas_daily_readings',
    gasCompanyMonthly: 'gas_company_monthly',
    targets: 'targets',
    benchmarks: 'benchmarks',
    importAliases: 'import_aliases',
    importTemplates: 'import_templates',
    importUploads: 'import_uploads',
    furnaces: 'furnaces',
    lines: 'lines',
    products: 'products',
  },
  storage: {
    importFiles: 'import-files',
  },
  productionRecords: {
    workDate: 'work_date',
    deptLine: 'dept_line',
    shift: 'shift',
    orderNo: 'order_no',
    product: 'product',
    material: 'material',
    process: 'process',
    orderSize: 'order_size',
    workSize: 'work_size',
    orderWeight: 'order_weight',
    chargeWeight: 'charge_weight',
    furnaceCode: 'furnace_code',
    workHours: 'work_hours',
    workCount: 'work_count',
    tonPerHour: 'ton_per_hour',
    tonPerRun: 'ton_per_run',
    enteredByName: 'entered_by_name',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    createdBy: 'created_by',
    updatedBy: 'updated_by',
    // Legacy columns retained for compatibility with older records and screens.
    workMonth: 'work_month',
    lineCode: 'line_code',
    productName: 'product_name',
    plan: 'plan_ton',
    actual: 'actual_ton',
    hwangji: 'hwangji_ton',
    cogging: 'cogging_ton',
    reworkSelf: 'rework_self_ton',
    reworkQuality: 'rework_quality_ton',
    note: 'note',
    enteredByShift: 'entered_by_shift',
  },
  gasRecords: {
    ym: 'ym',
    furnaceCode: 'furnace_code',
    chargeWeightKg: 'charge_weight_kg',
    gasUsage: 'gas_usage',
    gasUnit: 'gas_unit',
    source: 'source',
    orderNo: 'order_no',
    note: 'note',
    createdBy: 'created_by',
    createdAt: 'created_at',
    enteredByName: 'entered_by_name',
    enteredByShift: 'entered_by_shift',
  },
  gasDailyReadings: {
    date: 'date',
    furnaceCode: 'furnace_code',
    shift: 'shift',
    value: 'value',
    orderNo: 'order_no',
    createdBy: 'created_by',
    createdAt: 'created_at',
    enteredByName: 'entered_by_name',
    enteredByShift: 'entered_by_shift',
  },
  gasCompanyMonthly: {
    ym: 'ym',
    chargeWeightKg: 'charge_weight_kg',
    gasUsage: 'gas_usage',
    createdBy: 'created_by',
    createdAt: 'created_at',
  },
  targets: {
    scope: 'scope',
    ref: 'ref',
    metric: 'metric',
    targetValue: 'target_value',
    note: 'note',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  benchmarks: {
    org: 'org',
    metric: 'metric',
    scope: 'scope',
    value: 'value',
    createdAt: 'created_at',
  },
  importAliases: {
    datasetKey: 'dataset_key',
    canonicalField: 'canonical_field',
    aliasText: 'alias_text',
    active: 'active',
    note: 'note',
    createdBy: 'created_by',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  importTemplates: {
    name: 'name',
    datasetKey: 'dataset_key',
    sheetRules: 'sheet_rules',
    mappingJson: 'mapping_json',
    signatureJson: 'signature_json',
    active: 'active',
    createdBy: 'created_by',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  importUploads: {
    datasetKey: 'dataset_key',
    sheetName: 'sheet_name',
    fileName: 'file_name',
    storageBucket: 'storage_bucket',
    storagePath: 'storage_path',
    fileHash: 'file_hash',
    fileSize: 'file_size',
    layout: 'layout',
    rowCount: 'row_count',
    savedCount: 'saved_count',
    failedCount: 'failed_count',
    warningCount: 'warning_count',
    templateName: 'template_name',
    mappingJson: 'mapping_json',
    summaryJson: 'summary_json',
    createdBy: 'created_by',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
} as const

export const DB_CONFLICT_KEYS = {
  productionRecords: 'work_date,order_no,process',
  gasRecords: 'ym,furnace_code',
  gasDailyReadings: 'date,furnace_code,shift',
  gasCompanyMonthly: 'ym',
  targets: 'scope,ref,metric',
  benchmarks: 'org,metric,scope',
  importAliases: 'dataset_key,canonical_field,alias_text',
  importTemplates: 'dataset_key,name',
  importUploads: 'dataset_key,sheet_name,file_name',
} as const
