export const DB = {
  tables: {
    productionRecords: 'production_records',
    gasRecords: 'gas_records',
    gasDailyReadings: 'gas_daily_readings',
    gasCompanyMonthly: 'gas_company_monthly',
    furnaces: 'furnaces',
    lines: 'lines',
    products: 'products',
  },
  productionRecords: {
    workMonth: 'work_month',
    lineCode: 'line_code',
    productName: 'product_name',
    shift: 'shift',
    plan: 'plan_ton',
    actual: 'actual_ton',
    hwangji: 'hwangji_ton',
    cogging: 'cogging_ton',
    reworkSelf: 'rework_self_ton',
    reworkQuality: 'rework_quality_ton',
    workHours: 'work_hours',
    workCount: 'work_count',
    note: 'note',
    createdBy: 'created_by',
    createdAt: 'created_at',
    updatedBy: 'updated_by',
    updatedAt: 'updated_at',
    enteredByName: 'entered_by_name',
    enteredByShift: 'entered_by_shift',
  },
  gasRecords: {
    ym: 'ym',
    furnaceCode: 'furnace_code',
    chargeWeightKg: 'charge_weight_kg',
    gasUsage: 'gas_usage',
    gasUnit: 'gas_unit',
    source: 'source',
    orderNo: 'order_no',
    note: 'note',
    createdBy: 'created_by',
    createdAt: 'created_at',
    enteredByName: 'entered_by_name',
    enteredByShift: 'entered_by_shift',
  },
  gasDailyReadings: {
    date: 'date',
    furnaceCode: 'furnace_code',
    shift: 'shift',
    value: 'value',
    orderNo: 'order_no',
    createdBy: 'created_by',
    createdAt: 'created_at',
    enteredByName: 'entered_by_name',
    enteredByShift: 'entered_by_shift',
  },
} as const

export const DB_CONFLICT_KEYS = {
  productionRecords: 'work_month,line_code,product_name,shift',
  gasRecords: 'ym,furnace_code',
  gasDailyReadings: 'date,furnace_code,shift',
} as const
